### ISSUE TITLE
ldap_connect

### ISSUE THREAD

**Issue by JordanDalton** [kbanman/laravel-ldapauth#1]
In the event a user enters invalid credentials the following exception is encountered:

Could not bind to AD: [Removed]: Invalid credentials

**Comment by kbanman** [comment]
You're referring to invalid control credentials, right?

I figured that an exception was warranted in that case because without those credentials the system doesn't work at all.

**Comment by JordanDalton** [comment]
Correct. Though it is proper for the host to run form validation checks, some may also encounter this. Great library regardless. I'm using it for a project here at work.
