### ISSUE TITLE
problem when usings an AD which uses subdomain-names

### ISSUE THREAD

**Issue by roelpaesen** [kbanman/laravel-ldapauth#3]
When using an AD that uses subdomains for verification, it won't work.

For example: our domain to auhtenticate against is something like this:
subdomain.domain.com

How to fix:
in ldap.php, replace lines 110-113 with something like this:
----------------8<---------------------
            $temp = "";
            $domainarray = explode(".", $config['domain']);
            foreach($domainarray as $part){
                $temp = $temp.",dc=".$part;
            }
            $config['basedn'] = substr($temp,1);
----------------8<---------------------

**Comment by kbanman** [comment]
Thanks for catching this, and sorry it took so long for me to address this. Fixed in fb69608754fd79140c69bf5d661cfe529ba21b0e
